name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "d3b1a544-b976-40db-bce1-201b9351c174"
database_name = "memos-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "a7362cdd1d1a40fc944a5cd4112aeef6"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-r2-bucket"
preview_bucket_name = "notes-files-preview"

[vars]
USERNAME = "admin"
PASSWORD = "test123"
